#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorNone)
#pragma config(Sensor, dgtl2,  button,         sensorNone)
#pragma config(Sensor, dgtl3,  rotaryEncoder,  sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ultraSound,     sensorSONAR_inch)
#pragma config(Sensor, dgtl12, LED,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Task 01, Ian Mckibben

void norm() {
	while(SensorValue[limitSwitch] == 1) {
		untilDark(600, lightSensor);
		turnFlashlightOn(flashlight);
		untilLight(600, lightSensor);
		turnFlashlightOff(flashlight);
	}
}

void Xnorm() {
	while(true) {
		untilLight(600, lightSensor);
		turnFlashlightOn(flashlight);
		untilDark(600, lightSensor);
		turnFlashlightOff(flashlight);
	}
}


task main()
{
	norm();
}
